const CREATED = "CREATED";
const DISABLED = "DISABLED";
const BUILDING = "BUILDING";
const SUCCESS = "SUCCESS";
const FAILURE = "FAILURE";
const ABORTED = "ABORTED";
const UNSTABLE = "UNSTABLE";
const NONE = "";
const INQUEUE = "IN QUEUE";

module.exports = {
  CREATED,
  INQUEUE,
  DISABLED,
  BUILDING,
  SUCCESS,
  NONE,
  FAILURE,
  ABORTED,
  UNSTABLE,
};
